version: "3.9"

services:
  api_service:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started

  database:
    image: postgres:16-alpine
    env_file:
      - .env
    healthcheck:
      test: sh -c "pg_isready -U db_user -d db_name"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    env_file:
      - .env
    entrypoint: celery
    command: -A netology_pd_diplom worker --loglevel=info
    depends_on:
      - redis