version: "2.6.0"

services:
  api_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_password
    command:
      ["python manage.py migrate", "python manage.py runserver 0.0.0.0:8000"]
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      
    




  redis:
    image: redis
    ports:
      - "6379:6379"